#!/usr/bin/env bash

msg="É preciso informar um comando válido!"

[[ $# -ne 1 ]] && echo $msg && exit 1

help $1 &> /dev/null

[[ $? -eq 0 ]] && echo "$1 é interno!" || echo "$1 não é interno!"

exit 0
