#!/usr/bin/env bash

alunos="João Maria Luis Carlos"
for nome in $alunos; do
	echo $nome
done

frutas=("banana" "laranja" "mamão papaya")
for fruta in "${frutas[@]}"; do
	echo $fruta
done

for fruta in "${!frutas[@]}"; do
	echo $fruta
done

declare -A carros
carros[vw]="Fusca"
carros[fiat]="Palio"
carros[ford]="Corcel"

for carro in "${carros[@]}"; do 
	echo $carro
done

for carro in "${!carros[@]}"; do
	echo $carro
done

touch teste{1..3}.txt

for arquivo in *.txt; do
	echo $arquivo
done

for n in {1..5}; do
	echo $n
done

for n in {1..10}; do
	[[ $n -gt 5 ]] && break || echo $n
done

for n in {1..10}; do
	[[ $n -lt 6 ]] && continue
	echo $n
done
