#!/usr/bin/env bash

let numero=10
let numero+=3
let numero*=2

echo $numero

notapos=8
echo $((notapos++))

echo $notapos

notapre=8

echo $((++notapre))
echo $notapre

let nota=2
echo $nota

let nota=nota+5
echo $nota
