#!/usr/bin/env bash

n=0
while [[ $n -lt 5 ]]; do
	echo $n
	((n++))
done

while true; do
	read -p "Digite qualquer coisa ou Q para sair: " str
	[[ "$str" = [qQ] ]] && echo Saindo... && break \
		|| echo "VOcê digitou $str"
done
