#!/usr/bin/env bash

frutas=("banana" "laranja" "abacate")

while true; do
	clear
	echo "1. Banana"
	echo "2. Laranja"
	echo "3. Abacate"
	echo "4. Sair"
	read -p "Escolha o número da sua opção " opt
	[[ $opt -eq 4 ]] && break
	echo "Você escolheu ${frutas[$(($opt -1))]}."
	read -p "Tecle algo para continuar..." cont
done

